services:
  api:
    build: api
    ports:
      - "8080:8080"
    environment:
      - BUFRO_POSTGRES_HOST=postgres
      - BUFRO_POSTGRES_PORT=5432
      - BUFRO_POSTGRES_USER=bufro
      - BUFRO_POSTGRES_PASSWORD=postgres
      - BUFRO_POSTGRES_DB=bufro
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=bufro
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bufro
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "bufro", "-U", "bufro"]
      interval: 5s
      timeout: 5s
      retries: 5