services:
  api:
    build: api
    ports:
      - "8080:8080"
    environment:
      - BUFRO_POSTGRES_HOST=postgres
      - BUFRO_POSTGRES_PORT=5432
      - BUFRO_POSTGRES_USER=bufro
      - BUFRO_POSTGRES_PASSWORD=postgres
      - BUFRO_POSTGRES_DB=bufro
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=bufro
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bufro
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "bufro", "-U", "bufro"]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_BOOTSTRAP_REALM_NAME=bufro

    command: start-dev
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
