// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: bufro.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BufType int32

const (
	BufType_BUF_TYPE_UNKNOWN BufType = 0
	BufType_BUF_TYPE_IMAGE   BufType = 1
	BufType_BUF_TYPE_VIDEO   BufType = 2
)

// Enum value maps for BufType.
var (
	BufType_name = map[int32]string{
		0: "BUF_TYPE_UNKNOWN",
		1: "BUF_TYPE_IMAGE",
		2: "BUF_TYPE_VIDEO",
	}
	BufType_value = map[string]int32{
		"BUF_TYPE_UNKNOWN": 0,
		"BUF_TYPE_IMAGE":   1,
		"BUF_TYPE_VIDEO":   2,
	}
)

func (x BufType) Enum() *BufType {
	p := new(BufType)
	*p = x
	return p
}

func (x BufType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BufType) Descriptor() protoreflect.EnumDescriptor {
	return file_bufro_proto_enumTypes[0].Descriptor()
}

func (BufType) Type() protoreflect.EnumType {
	return &file_bufro_proto_enumTypes[0]
}

func (x BufType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BufType.Descriptor instead.
func (BufType) EnumDescriptor() ([]byte, []int) {
	return file_bufro_proto_rawDescGZIP(), []int{0}
}

type CreateBufRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type BufType `protobuf:"varint,1,opt,name=type,proto3,enum=BufType" json:"type,omitempty"`
	Data []byte  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CreateBufRequest) Reset() {
	*x = CreateBufRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bufro_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBufRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBufRequest) ProtoMessage() {}

func (x *CreateBufRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bufro_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBufRequest.ProtoReflect.Descriptor instead.
func (*CreateBufRequest) Descriptor() ([]byte, []int) {
	return file_bufro_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBufRequest) GetType() BufType {
	if x != nil {
		return x.Type
	}
	return BufType_BUF_TYPE_UNKNOWN
}

func (x *CreateBufRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateBufResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateBufResponse) Reset() {
	*x = CreateBufResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bufro_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBufResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBufResponse) ProtoMessage() {}

func (x *CreateBufResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bufro_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBufResponse.ProtoReflect.Descriptor instead.
func (*CreateBufResponse) Descriptor() ([]byte, []int) {
	return file_bufro_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBufResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bufro_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_bufro_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_bufro_proto_rawDescGZIP(), []int{2}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetUserBufsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit  int64  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset int64  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *GetUserBufsRequest) Reset() {
	*x = GetUserBufsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bufro_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserBufsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBufsRequest) ProtoMessage() {}

func (x *GetUserBufsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bufro_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBufsRequest.ProtoReflect.Descriptor instead.
func (*GetUserBufsRequest) Descriptor() ([]byte, []int) {
	return file_bufro_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserBufsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserBufsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetUserBufsRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type Buf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId string  `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type   BufType `protobuf:"varint,3,opt,name=type,proto3,enum=BufType" json:"type,omitempty"`
	Data   []byte  `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Buf) Reset() {
	*x = Buf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bufro_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Buf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Buf) ProtoMessage() {}

func (x *Buf) ProtoReflect() protoreflect.Message {
	mi := &file_bufro_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Buf.ProtoReflect.Descriptor instead.
func (*Buf) Descriptor() ([]byte, []int) {
	return file_bufro_proto_rawDescGZIP(), []int{4}
}

func (x *Buf) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Buf) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Buf) GetType() BufType {
	if x != nil {
		return x.Type
	}
	return BufType_BUF_TYPE_UNKNOWN
}

func (x *Buf) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetUserBufsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bufs []*Buf `protobuf:"bytes,1,rep,name=bufs,proto3" json:"bufs,omitempty"`
}

func (x *GetUserBufsResponse) Reset() {
	*x = GetUserBufsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bufro_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserBufsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBufsResponse) ProtoMessage() {}

func (x *GetUserBufsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bufro_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBufsResponse.ProtoReflect.Descriptor instead.
func (*GetUserBufsResponse) Descriptor() ([]byte, []int) {
	return file_bufro_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserBufsResponse) GetBufs() []*Buf {
	if x != nil {
		return x.Bufs
	}
	return nil
}

var File_bufro_proto protoreflect.FileDescriptor

var file_bufro_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x62, 0x75, 0x66, 0x72, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x44, 0x0a,
	0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1c, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x08, 0x2e, 0x42, 0x75, 0x66, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x23, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x66,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x21, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x5b, 0x0a, 0x12, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x75, 0x66, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x60, 0x0a, 0x03, 0x42, 0x75, 0x66, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x08, 0x2e, 0x42, 0x75, 0x66, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2f, 0x0a, 0x13, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x75, 0x66, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x04, 0x62, 0x75, 0x66, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x04, 0x2e, 0x42, 0x75, 0x66, 0x52, 0x04, 0x62, 0x75, 0x66, 0x73, 0x2a, 0x47, 0x0a, 0x07, 0x42,
	0x75, 0x66, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x42, 0x55, 0x46, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e,
	0x42, 0x55, 0x46, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x49, 0x4d, 0x41, 0x47, 0x45, 0x10, 0x01,
	0x12, 0x12, 0x0a, 0x0e, 0x42, 0x55, 0x46, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x56, 0x49, 0x44,
	0x45, 0x4f, 0x10, 0x02, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x70, 0x6b, 0x75, 0x6c, 0x69, 0x6b, 0x30, 0x2f, 0x62, 0x75, 0x66, 0x72, 0x6f,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bufro_proto_rawDescOnce sync.Once
	file_bufro_proto_rawDescData = file_bufro_proto_rawDesc
)

func file_bufro_proto_rawDescGZIP() []byte {
	file_bufro_proto_rawDescOnce.Do(func() {
		file_bufro_proto_rawDescData = protoimpl.X.CompressGZIP(file_bufro_proto_rawDescData)
	})
	return file_bufro_proto_rawDescData
}

var file_bufro_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bufro_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_bufro_proto_goTypes = []any{
	(BufType)(0),                // 0: BufType
	(*CreateBufRequest)(nil),    // 1: CreateBufRequest
	(*CreateBufResponse)(nil),   // 2: CreateBufResponse
	(*Error)(nil),               // 3: Error
	(*GetUserBufsRequest)(nil),  // 4: GetUserBufsRequest
	(*Buf)(nil),                 // 5: Buf
	(*GetUserBufsResponse)(nil), // 6: GetUserBufsResponse
}
var file_bufro_proto_depIdxs = []int32{
	0, // 0: CreateBufRequest.type:type_name -> BufType
	0, // 1: Buf.type:type_name -> BufType
	5, // 2: GetUserBufsResponse.bufs:type_name -> Buf
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_bufro_proto_init() }
func file_bufro_proto_init() {
	if File_bufro_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bufro_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CreateBufRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bufro_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateBufResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bufro_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bufro_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetUserBufsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bufro_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Buf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bufro_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetUserBufsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bufro_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bufro_proto_goTypes,
		DependencyIndexes: file_bufro_proto_depIdxs,
		EnumInfos:         file_bufro_proto_enumTypes,
		MessageInfos:      file_bufro_proto_msgTypes,
	}.Build()
	File_bufro_proto = out.File
	file_bufro_proto_rawDesc = nil
	file_bufro_proto_goTypes = nil
	file_bufro_proto_depIdxs = nil
}
